spring:
  profiles:
    active: dev

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:dGhpc2lzYXZlcnlsb25nYW5kc2VjdXJlc2VjcmV0a2V5Zm9ybXVzaWZ5YXBwbGljYXRpb25qd3R0b2tlbmdlbmVyYXRpb25hbmR2YWxpZGF0aW9u}
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: INFO
    com.musify: INFO
